#!/usr/bin/env python
# -*- Mode: Python; tab-width: 4; py-indent-offset: 4; -*-

import sys, os
import string

sys.path.append('/auto/share/lib');
from elog.elogdb import DB

if len(sys.argv) > 1 and (sys.argv[1] == '-d' or sys.argv[1] == '-dir'):
    dir = 1
    sys.argv[1] = ''
else:
    dir = 0

result = {}
if len(sys.argv) > 1:
    target = '%' + string.join(sys.argv[1:],'%') + '%'
    # convert to regexp:
    target = target.replace('%', '.*')
    db = DB()
    # use REGEXP instead of LIKE
    (ok, rows) = db.q('SELECT src FROM dfile WHERE src REGEXP "%s"'
                      ' AND NOT crap '
                      ' ORDER BY date, right(src, 3)' % target)
    dlist = {}
    for r in rows:
        if dir:
            d = os.path.dirname(r['src'])
            if not dlist.has_key(d):
                print os.path.dirname(r['src'])
                dlist[d] = 1
        else:
            print r['src']

else:
    sys.stderr.write('usage: dbfind [-d] partial file/exper name\n')
    sys.stderr.write('  look for pype datafiles using the lab database\n')
    sys.stderr.write('  -d prints directory name only\n')


