#!/bin/sh
#
# run a local "quick-test" version of elog in place using
# a test database (mlabdata_test instead of mlabdata)
#
# if called with -r argument, restore a virgin database first
#  virgin db was created using 'make testdata', which does
# 

make test-inplace

if [ `hostname` = sage ]; then
    if [ "$1" = "-r" ]; then
	shift
	mysqladmin --force -hlocalhost -uroot -pf00lish1 drop mlabdata_test
	mysqladmin --force -hlocalhost -uroot -pf00lish1 create mlabdata_test
	gunzip <testdata.sql.gz | mysql -uroot -pf00lish1 mlabdata_test
    fi
    env ELOG_HOST=localhost ELOG_DB=mlabdata_test \
	ELOG_USER=root ELOG_PASSWD=f00lish1 ./elog $*
else
    if [ "$1" = "-r" ]; then
	shift
	make testdata
	mysqladmin --force -hsql -umlab -pmlab drop mlabdata_test
	mysqladmin --force -hsql -umlab -pmlab create mlabdata_test
	gunzip <testdata.sql.gz | mysql -hsql -umlab -pmlab mlabdata_test
    fi
    env ELOG_DB=mlabdata_test ./elog $*
fi

