#!/bin/sh
#
# run a local "quick-test" version of elog in place using
# a test database (mlabdata_test instead of mlabdata)
#
# if called with -r argument, restore a virgin database first
#  virgin db was created using 'make testdata', which does
#
# if called with -a argument, runs elogattach
#
# otherwise runs elog
# 

make test-inplace

host=sql; user=mlab;pass=mlab
if [ `hostname` = sage ]; then
  host=localhost; user=root; pass=f00lish1
fi
if [ "$1" = "-r" ]; then
  shift
  mysqladmin --force -h$host -u$user -p$pass drop mlabdata_test
  mysqladmin --force -h$host -u$user -p$pass create mlabdata_test
  gunzip <testdata.sql.gz | mysql -h$host -u$user -p$pass mlabdata_test
  exit
fi
if [ "$1" = "-a" ]; then
  echo "testing elogatt"
  env ELOG_HOST=$host ELOG_USER=$user ELOG_PASSWD=$pass \
      ELOG_DB=mlabdata_test ./elogatt $*
else
  echo "testing elog"
  env ELOG_HOST=$host ELOG_USER=$user ELOG_PASSWD=$pass \
      ELOG_DB=mlabdata_test ./elog $*
fi
