#!/bin/sh
#
# run a local "quick-test" version of elog in place using
# a test database (mlabdata_test instead of mlabdata)
#
# if called with -r argument, restore a virgin database first
#  virgin db was created using 'make testdata', which does
#
# if called with -a argument, runs elogattach
#
# otherwise runs elog
# 

. ./sqlconfig.sh

if [ "$1" = "-r" ]; then
  # refresh _test databae
  shift
  mysqldump -hsql -u${USER} -p${PASS} --add-drop-database --databases ${DB} \
		| sed s/${DB}/${DB}_test/g \
		| gzip >testdata.sql.gz
  mysqladmin --force -h${HOST} -u${USER} -p${PASS} drop ${DB}_test
  mysqladmin --force -h${HOST} -u${USER} -p${PASS} create ${DB}_test
  gunzip <testdata.sql.gz | mysql -h${HOST} -u${USER} -p${PASS} ${DB}_test
  exit
fi

make test
echo "[running test copy of elog on ${DB}_test]"
env ELOG_HOST=${HOST} ELOG_USER=${USER} ELOG_PASS=${PASS} \
      ELOG_DB=${DB}_test ./elog $*
