#!/bin/sh

if [ "$1" = "" ]; then
  d=$(date +%Y-%m)
else
  d=$1
fi
/auto/share/pypeextra/elog-gen-monthly-html $d > /auto/www/elogs/$d.html
if [ "$1" = "" ]; then
  cp /auto/www/elogs/$d.html /auto/www/elogs/monthly.html
fi


